IntegrationsInsert/IntegrationsInsert/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IntegrationsInsert.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Principal;
using Microsoft.AspNetCore.Authentication;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;

namespace IntegrationsInsert.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Index(SuccessModel model)
        {

            var wi = (WindowsIdentity)User.Identity;

            PrincipalContext pc = new PrincipalContext(ContextType.Domain, "BH");
            var src = UserPrincipal.FindByIdentity(pc, User.Identity.Name).GetGroups(pc);


            var groups = src.Select(x => x).Select(x => x.Name).Where(y => y.Contains("BHSQL Corepoint Integrations Users")).ToList();


            if (groups.Any())
            {
                ViewData["ShowInsert"] = true;
            }
            else
            {
                ViewData["ShowInsert"] = false;
            }

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(Exception ex)
        {
            return View(new ErrorViewModel { RequestId = Activity.Current.Id ?? HttpContext.TraceIdentifier, exOutputMessage = ex.Message });
        }
    }
}

IntegrationsInsert/IntegrationsInsert/Controllers/IntegrationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntegrationsInsert.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data;
using OfficeOpenXml;
using System.Transactions;
using Microsoft.Extensions.Configuration;
using IntegrationsInsert.data;
using IntegrationsInsert.Utils;
//using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using System.Text;
using NLog;

namespace IntegrationsInsert.Controllers
{
    public class IntegrationsController : Controller
    {
        public IConfiguration _config;
        private readonly DevContext _devContext;
        private readonly DevAuditContext _devAuditContext;
        private readonly ProdContext _prodContext;
        private readonly ProdAuditContext _prodAuditContext;
        private readonly string DeployedEnv;
        //private readonly string LoggingPath;
        //private readonly ILogger _logger;
        private static readonly Logger _logger = NLog.LogManager.GetCurrentClassLogger();
        private List<string> errors = new List<string>();
        public IntegrationsController(IConfiguration c, DevContext dContext, DevAuditContext dAuditContext, ProdContext pContext, ProdAuditContext pAuditContext)
        {
            _config = c;
            _devContext = dContext;
            _devAuditContext = dAuditContext;
            _prodContext = pContext;
            _prodAuditContext = pAuditContext;
            //_logger = logger.CreateLogger("IntegrationInsert.IntegrationInsert.IntegrationsController");
            DeployedEnv = _config.GetSection("DeployedEnvironment").Value;
            //LoggingPath = _config.GetSection("logPath").Value;

            var config = new NLog.Config.LoggingConfiguration();

            var orFile = new NLog.Targets.FileTarget("logfile") { FileName = "IntegrationsInsert.log" };
            config.AddRule(LogLevel.Info, LogLevel.Fatal, orFile);
            LogManager.Configuration = config;
        }
        [Authorize]
        public IActionResult Insert()
        {
            var name = HttpContext.User.Identity.Name;


            return View();
        }
        [Authorize]
        public IActionResult InsertToDoctors()
        {
            var name = HttpContext.User.Identity.Name;
            Doctors model = new Doctors();

            return View(model);
        }
        [Authorize]
        public IActionResult InsertToGPSMProviders()
        {
            var name = HttpContext.User.Identity.Name;
            GE_GPMS_Providers model = new GE_GPMS_Providers();

            return View(model);
        }
        [Authorize]
        public IActionResult InsertToTouchworks()
        {
            var name = HttpContext.User.Identity.Name;
            TouchworksProviders model = new TouchworksProviders();

            return View(model);
        }
        [Authorize]
        public IActionResult Error(ErrorViewModel model)
        {
            return View(model);
        }
        public void ErrorAudit(ErrorAudit audit)
        {
            bool devsuccessful = false;
            if (DeployedEnv == "Dev")
            {
                using (var t = _devAuditContext.Database.BeginTransaction())
                {
                    try
                    {
                        ErrorAudit e = new ErrorAudit();
                        e.AuditUser = audit.AuditUser;
                        e.Error = audit.Error;
                        e.ErrorTime = audit.ErrorTime;
                    _devAuditContext.ErrorAudit.Add(e);
                    _devAuditContext.SaveChanges();

                        t.Commit();
                    }
                    catch (Exception e)
                    {
                        t.Rollback();
                        //Logging.LogMessage("Exception occurred while adding Error Audit:(Dev) " + audit.Error, LoggingPath);
                        _logger.Info("Exception occurred while adding Error Audit:(Dev) " + audit.Error);
                    }
                }
            }
            else
            {
                using (var t = _devAuditContext.Database.BeginTransaction())
                {
                    try
                    {
                        ErrorAudit e = new ErrorAudit();
                        e.AuditUser = audit.AuditUser;
                        e.Error = audit.Error;
                        e.ErrorTime = audit.ErrorTime;
                    _devAuditContext.ErrorAudit.Add(e);
                    _devAuditContext.SaveChanges();

                        t.Commit();
                        devsuccessful = true;
                    }
                    catch (Exception e)
                    {
                        t.Rollback();
                        //Logging.LogMessage("Exception occurred while adding Error Audit:(Dev) " + audit.Error, LoggingPath);
                        _logger.Info("Exception occurred while adding Error Audit:(Dev) " + audit.Error);
                    }
                }
                if (devsuccessful)
                {
                    using (var t = _prodAuditContext.Database.BeginTransaction())
                    {
                        try
                        {
                            ErrorAudit e = new ErrorAudit();
                            e.AuditUser = audit.AuditUser;
                            e.Error = audit.Error;
                            e.ErrorTime = audit.ErrorTime;
                        _prodAuditContext.ErrorAudit.Add(e);
                        _prodAuditContext.SaveChanges();

                            t.Commit();
                        }
                        catch (Exception e)
                        {
                            t.Rollback();
                            //Logging.LogMessage("Exception occurred while adding Error Audit:(Prod) " + audit.Error, LoggingPath);
                            _logger.Info("Exception occurred while adding Error Audit:(Prod) " + audit.Error);
                        }
                    }
                }
            }
        }
        public bool DoctorAudit(Doctors model)
        {
            if (DeployedEnv == "Dev")
            {
                using (var t = _devAuditContext.Database.BeginTransaction())
                {
                    try
                    {
                        DoctorsAudit audit = new DoctorsAudit();
                        audit.ChangeNotes = model.ChangeNotes;
                        audit.PhysicianGroup = model.PhysicianGroup;
                        audit.ProviderActive = model.ProviderActive;
                        audit.ProviderName = model.ProviderName;
                        audit.ProviderNpi = model.ProviderNpi;
                        audit.ProviderPasnbr = model.ProviderPasnbr;
                        audit.ProviderUserId = model.ProviderUserId;
                        audit.AuditActivity = "I";
                        audit.AuditTimeStamp = DateTime.Now;
                        audit.AuditUser = User.Identity.Name;

                    _devAuditContext.DoctorsAudit.Add(audit);
                    _devAuditContext.SaveChanges();


                        t.Commit();
                        return true;
                    }
                    catch (Exception ex)
                    {
                        t.Rollback();
                        //Logging.LogMessage("Exception occurred while adding Doctors Audit (Dev): " + model.ProviderName, LoggingPath);
                        _logger.Info("Exception occurred while adding Doctors Audit (Dev): " + model.ProviderName);

                        ErrorAudit(new Models.ErrorAudit { AuditUser = User.Identity.Name, Error = ex.Message.ToString(), ErrorTime = DateTime.Now });
                        return false;
                    }
                }
            }
            else
            {
                using (var t = _devAuditContext.Database.BeginTransaction())
                {
                    try
                    {
                        DoctorsAudit audit = new DoctorsAudit();
                        audit.ChangeNotes = model.ChangeNotes;
                        audit.PhysicianGroup = model.PhysicianGroup;
                        audit.ProviderActive = model.ProviderActive;
                        audit.ProviderName = model.ProviderName;
                        audit.ProviderNpi = model.ProviderNpi;
                        audit.ProviderPasnbr = model.ProviderPasnbr;
                        audit.ProviderUserId = model.ProviderUserId;
                        audit.AuditActivity = "I";
                        audit.AuditTimeStamp = DateTime.Now;
                        audit.AuditUser = User.Identity.Name;

                        _devAuditContext.DoctorsAudit.Add(audit);
                        _devAuditContext.SaveChanges();


                        t.Commit();
                    }
                    catch (Exception ex)
                    {
                        t.Rollback();
                        //Logging.LogMessage("Exception occurred while adding Doctors Audit:(Dev) " + model.ProviderName, LoggingPath);
                        _logger.Info("Exception occurred while adding Doctors Audit:(Dev) " + model.ProviderName);

                        ErrorAudit(new Models.ErrorAudit { AuditUser = User.Identity.Name, Error = ex.Message.ToString(), ErrorTime = DateTime.Now });
                        return false;
                    }
                }
                using (var t = _prodAuditContext.Database.BeginTransaction())
                {
                    try
                    {
                        DoctorsAudit audit = new DoctorsAudit();
                        audit.ChangeNotes = model.ChangeNotes;
                        audit.PhysicianGroup = model.PhysicianGroup;

IntegrationsInsert/IntegrationsInsert/Views/Home/Index.cshtml
@model SuccessModel

@{
    ViewData["Title"] = "Home";
}
@if (!String.IsNullOrWhiteSpace(Model.SuccessMessage))
{
     <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>
                    @Model.SuccessMessage
                </h3>
            </div>
        </div>
         @if (Model.SuccessMessage.Equals("Inserted from Excel"))
         {
     <div class="row">
         <div class="col-md-4">
             <h4>Doctor Table Dev</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumDoctorRecordsDev Record(s) Inserted.
                 </div>
             </div>
         </div>
         <hr />
         <div class="col-md-4">
             <h4>GPMS Table Dev</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumGPMSRecordsDev Record(s) Inserted.
                 </div>
             </div>
         </div>
         <hr />
         <div class="col-md-4">
             <h4>Touchworks Table Dev</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumTouchworksRecordsDev Record(s) Inserted.
                 </div>
             </div>
         </div>
     </div>  
     <div class="row">
         <div class="col-md-4">
             <h4>Doctor Table Prod</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumDoctorRecordsProd Record(s) Inserted.
                 </div>
             </div>
         </div>
         <hr />
         <div class="col-md-4">
             <h4>GPMS Table Prod</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumGPMSRecordsProd Record(s) Inserted.
                 </div>
             </div>
         </div>
         <hr />
         <div class="col-md-4">
             <h4>Touchworks Table Prod</h4>
             <div class="row">
                 <div class="col-md-12">
                     @Model.NumTouchworksRecordsProd Record(s) Inserted.
                 </div>
             </div>
         </div>
     </div>
         }
    </div>
}
    <hr/>
    <hr/>
   
@if ((bool)ViewData["ShowInsert"])
{
<div class="container">
    <div class="rowspace"></div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="display-4">Welcome to Integrations Managment</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            @Html.ActionLink("Upload Excel", "UploadExcel", "Integrations", null, new { @class = "btn btn-primary buttonspace" })
        </div>
        <div class="col-md-12 text-center">
            @Html.ActionLink("Insert Doctor Record", "InsertToDoctors", "Integrations", null, new { @class = "btn btn-primary buttonspace" })
        </div>
        <div class="col-md-12 text-center">
            @Html.ActionLink("Insert GPMS Provider Record", "InsertToGPSMProviders", "Integrations", null, new { @class = "btn btn-primary buttonspace" })
        </div>
        <div class="col-md-12 text-center">
            @Html.ActionLink("Insert Touchworks Provider Record", "InsertToTouchworks", "Integrations", null, new { @class = "btn btn-primary buttonspace" })
        </div>
    </div>
</div>
   
}
else
{
    <div>User not in the correct group!</div>
}